name: Build FlowForge Docs (Deprecated)

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deprecated:
    runs-on: ubuntu-latest
    steps:
      - name: Deprecated
        run: |
          echo "This workflow is deprecated."
          echo "Use shipyard-microtools/.github/workflows/deploy.yml instead."
